### ISSUE TITLE
add theme halo-theme-higan-hz to store

### ISSUE THREAD

**Issue by HowieHz** [halo-sigs/awesome-halo#104]
辛苦帮忙审批下，并发布到应用商店。 #102
提 pr 的时候忘记附言了不好意思😭

**Comment by ruibaby** [comment]
已发布。

https://www.halo.run/store/apps/app-homxf

**Comment by HowieHz** [comment]
> 已发布。
> 
> https://www.halo.run/store/apps/app-homxf

感谢
