### ISSUE TITLE
【插件未更新】“无色界”插件原来我提交到readme里面了，说已经存在，但是实际上目前为止还是无法在应用市场中找到

### ISSUE THREAD

**Issue by carolcoral** [halo-sigs/awesome-halo#119]
【插件未更新】“无色界”插件原来我提交到readme里面了，说已经存在，但是实际上目前为止还是无法在应用市场中找到
https://github.com/guqing/halo-plugin-colorless

**Comment by ruibaby** [comment]
我们没有说过只要在此仓库列出就会上架到应用市场，这完全取决于作者是否需要。

/close

**Comment by guqing** [comment]
已经添加到应用市场 https://www.halo.run/store/apps/app-IbqRW
