### ISSUE TITLE
提交个bug,插件看板娘突然显示不了了

### ISSUE THREAD

**Issue by aling466** [halo-sigs/awesome-halo#122]
看板娘版本：1.2.1，
halo版本：2.18

问题：看板娘插件突然无法在桌面显示模型图片，即使重新安装插件也无法解决
docker后台日志无报错
![image](https://github.com/user-attachments/assets/2a8631c9-0d4c-4892-8788-30272065db45)
![image](https://github.com/user-attachments/assets/65806e26-792a-4594-a5b2-76f5b3c5f9dd)
![image](https://github.com/user-attachments/assets/9aff74dc-470e-46bc-900f-e6edd65dad96)
![image](https://github.com/user-attachments/assets/69c9737c-158d-4bbb-8ee7-82e00a405eff)

**Comment by ruibaby** [comment]
建议在 https://github.com/LIlGG/plugin-live2d 中提交。

/close
