### ISSUE TITLE
能否支持下腾讯云CDN和COS，腾讯云用1.x版本的希望尽快迁移到2.0halo版本当中，但是不支持腾讯云

### ISSUE THREAD

**Issue by ghost** [halo-sigs/awesome-halo#30]
能否支持下腾讯云CDN和COS，腾讯云用1.x版本的希望尽快迁移到2.0halo版本当中，但是不支持腾讯云

**Comment by JohnNiang** [comment]
不妨试试 S3 插件：<https://github.com/halo-sigs/plugin-s3>。
