### ISSUE TITLE
这个项目能否在每个项目说明后面增加更新时间和更新的最新版本

### ISSUE THREAD

**Issue by ghost** [halo-sigs/awesome-halo#37]
这个项目能否在每个项目说明后面增加更新时间和更新的最新版本，不用一个一个打开看~
十分感谢~

**Comment by HowieHz** [comment]
每行增加个最新commit提交的时间够用了
`https://img.shields.io/github/last-commit/:user/:repo`
文档:`https://shields.io/badges/git-hub-last-commit`

例如
`![GitHub last commit](https://img.shields.io/github/last-commit/halo-sigs/awesome-halo)`
![GitHub last commit](https://img.shields.io/github/last-commit/halo-sigs/awesome-halo)
