### ISSUE TITLE
建议出个站点备份的插件

### ISSUE THREAD

**Issue by govbk** [halo-sigs/awesome-halo#41]
跟1.x版本一样可以备份站点文章或者全站备份

**Comment by ruibaby** [comment]
已经在 https://github.com/halo-dev/halo/pull/4206 中支持。并且发布在了 2.8-rc.1：https://github.com/halo-dev/halo/releases/tag/v2.8.0-rc.1

**Comment by wenjing-xin** [comment]
> 已经在 [halo-dev/halo#4206](https://github.com/halo-dev/halo/pull/4206) 中支持。并且发布在了 2.8-rc.1：https://github.com/halo-dev/halo/releases/tag/v2.8.0-rc.1

测试
